### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by starfys** [MTSUMakers/ArcLightning#35]
**Please describe your issue.**
We need a login page

**Describe the solution you'd like**
- [ ] New file `login.html` inside `arclightning_web`
- [ ] Form with `username` and `password` fields
- [ ] On pressing submit, submit a `POST` request to `http://hostname/api/v1/signin?username=username&password=password`

**Comment by VirtualRcoder** [comment]
May i wok on this issue.
There are two folders arclightning_frontend and arclightning_backend.
There is no folder with name arclightning_web.
So, should i make login.html in arclightning_frontend.

**Comment by starfys** [comment]
Thank you for your interest, but this project is currently a class project for CSCI4700 at Middle Tennessee State University.

**Comment by VirtualRcoder** [comment]
Okay
