### ISSUE TITLE
[ARCADE BACKEND] access cookie for UI

### ISSUE THREAD

**Issue by starfys** [MTSUMakers/ArcLightning#44]
**Please describe your issue.**
We want to enforce the password on demonstration mode
**Describe the solution you'd like**
- [ ] if the password for the check_password endpoint is correct, return  `{'success': true, 'access_key': '64 random bytes encoded as hex'}` else, return `{'success': false}`
- [ ] Store this access key somewhere on the server.
- [ ] Store the time the key was generated
- [ ] Check the headers of all incoming requests to anything except `demonstration.html` and `/api/v1/check_password`. If they don't have the right key, redirect them to `demonstration.html`
- [ ] When checking headers, if the key is older than 12 hours, invalidate it.
- [ ] there is only one password for this.
- [ ] it should be stored manually as part of the config (#28)
- [ ] it should be salted and b2hashed

**Comment by sremedios** [comment]
> if the password for the check_password endpoint is correct, return {'success': true, 'access_key': '64 random bytes encoded as hex'} else, return {'success': false}

Will this map be used by the frontend at all, or is it solely for backend server use?

**Comment by starfys** [comment]
map?
