### ISSUE TITLE
Edit settings page

### ISSUE THREAD

**Issue by starfys** [MTSUMakers/ArcLightning#48]
**Please describe your issue.**
the reason we want to be able to log in with a web ui and qr code is so that users can save their settings

**Describe the solution you'd like**
form in the web frontend with:
- [ ] name: user's name. cap it at 200 bytes
- [ ] profile text color: color picker, used to display the name
- [ ] profile background color: color picker, used to display the name
- [ ] preview of `name` with `text color` and `background color`
- [ ] volume slider. corresponds to a floating point value from 0.0 to 1.0
*  if you have any other ideas, include them! Preferably no uploads, since we probably don't want to have to deal with hosting a file server with public upload
- [ ] submitting the form to `hostname/api/v1/edit_settings` with json body `{name, profile_fgcolor, profile_bgcolor, volume}`

**Comment by madagas-karrh** [comment]
So, sending a POST request to hostname/api/v1/edit_settings, but also should be using GET request to load data if the user has already set it.. what is the endpoint going to be for that?
